language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
sudo: false
cache:
  directories:
    - $HOME/buildout-cache
    - $HOME/parts/node
    - $HOME/.cache/pip
env:
  matrix:
    - CONF=travis.cfg
    - CONF=travis.cfg TEST_ALL=true
install:
  - pip install -r requirements.txt
  - easy_install -U zc.buildout==2.11.0
  - buildout -c $CONF annotate
  - buildout -N -t 3 -c $CONF || buildout -N -t 3 -c $CONF
script:
  - if [ $PYTHON_VERSION == 2.7 ]; then pip install docutils ; fi
  - if [ $PYTHON_VERSION == 2.7 ]; then pip install Pygments ; fi
  - if [ $PYTHON_VERSION == 2.7 ]; then python setup.py check -r -s ; fi
  - bin/code-analysis
  - bin/test
after_failure:
  - bin/flake8 --version
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version

