language: python
python:
  - 2.7
  - 3.4
sudo: false
cache:
  directories:
    - $HOME/buildout-cache
    - $HOME/parts/node
env:
  matrix:
    - CONF=travis.cfg
    - CONF=extras.cfg EXTRAS_INSTALLED=true
matrix:
  allow_failures:
    - python: 3.4
      env: CONF=extras.cfg EXTRAS_INSTALLED=true
install:
  - python bootstrap-buildout.py --setuptools-version=18.5
  - bin/buildout -c $CONF annotate
  - bin/buildout -N -t 3 -c $CONF
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls
after_failure:
  - bin/flake8 --version
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version
